name: java-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: self-hosted

    steps:
      - name: Gitcheckout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn clean package

      #- name: SonarQube Scan
       # run: mvn sonar:sonar \
        #  -Dsonar.host.url=${{ secrets.https://sonarcloud.io/}} \
         # -Dsonar.login=${{ secrets.e7820e5fa3fff62d96c876f45902fdf107fa5c63 }}