name: java-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: ubuntu-latest
    
    steps:
      - name: Gitcheckout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn clean package

      - name:  Build and sonar scan
      - run: mvn clean verify sonar:sonar -Dsonar.projectKey=devibanneaes_spring-petclinic -Dsonar.organization=devi -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
       
          
